services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - ragapp-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434 
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - ragapp-network
  
  setup:
    image: curlimages/curl:latest
    networks:
      - ragapp-network
    volumes:
      - ./scripts:/ragapp
    environment:
      - MODEL=${MODEL:-phi3:latest}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=cs50,cs101
      - DISTANCE_METRIC=Cosine
      - VECTOR_SIZE=768
    command: >
      /bin/sh -c 
      "chmod +x /ragapp/create_qdrant_collection.sh /ragapp/setup_ollama.sh &&
      /ragapp/create_qdrant_collection.sh &&
      /ragapp/setup_ollama.sh"
    depends_on:
      - qdrant
      - ollama

  ragapp-cs50:
    build: .
    image: ragapp/ragapp:latest
    entrypoint: ["/app/entrypoint.sh"]
    command: ["fastapi", "run", "main.py"]
    volumes:
      - ./config:/app/config
      - ./data:/app/data 
    labels:
      - ragapp.app_name=cs50
      - traefik.enable=true
      - traefik.http.services.ragapp-cs50.loadbalancer.server.port=8000
      - traefik.http.routers.ragapp-cs50.rule=PathPrefix(`/a/cs50`)
      - traefik.http.middlewares.ragapp-cs50-strip-path.stripprefix.prefixes=/a/cs50
      - traefik.http.routers.ragapp-cs50.middlewares=ragapp-cs50-strip-path
      - traefik.http.routers.ragapp-cs50-admin.rule=PathRegexp(`/a/cs50/admin`)
      - traefik.http.routers.ragapp-cs50-admin.middlewares=admin-auth,ragapp-cs50-strip-path
    environment:
      - BASE_URL=/a/cs50
      - VECTOR_STORE_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=cs50
      - QDRANT_API_KEY=""
      - MODEL_PROVIDER=ollama
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - EMBEDDING_MODEL=nomic-embed-text
      - EMBEDDING_DIM=768
      - MODEL=${MODEL:-phi3:latest}
    depends_on:
      - setup
    networks:
      - ragapp-network

  ragapp-cs101:
    build: .
    image: ragapp/ragapp:latest
    entrypoint: ["/app/entrypoint.sh"]
    command: ["fastapi", "run", "main.py"]
    volumes:
      - ./config:/app/config
      - ./data:/app/data 
    labels:
      - ragapp.app_name=cs101
      - traefik.enable=true
      - traefik.http.services.ragapp-cs101.loadbalancer.server.port=8000
      - traefik.http.routers.ragapp-cs101.rule=PathPrefix(`/a/cs101`)
      - traefik.http.middlewares.ragapp-cs101-strip-path.stripprefix.prefixes=/a/cs101
      - traefik.http.routers.ragapp-cs101.middlewares=ragapp-cs101-strip-path
      - traefik.http.routers.ragapp-cs101-admin.rule=PathRegexp(`/a/cs101/admin`)
      - traefik.http.routers.ragapp-cs101-admin.middlewares=admin-auth,ragapp-cs101-strip-path
    environment:
      - BASE_URL=/a/cs101
      - VECTOR_STORE_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=cs101
      - QDRANT_API_KEY=""
      - MODEL_PROVIDER=ollama
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - EMBEDDING_MODEL=nomic-embed-text
      - EMBEDDING_DIM=768
      - MODEL=${MODEL:-phi3:latest}
    depends_on:
      - setup
    networks:
      - ragapp-network
  
networks:
  ragapp-network:
    external: true
