services:
  admin-dashboard:
    image: ragapp/admin-dashboard
    build: src/manager
    command:
      - fastapi
      - run
      - main.py
      - --port
      - '80'
      - --root-path
      - /dashboard
    ports:
      - '8100:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.routers.admin-dashboard.rule=PathPrefix(`/dashboard`)
      - traefik.http.middlewares.admin-dashboard-stripprefix.stripprefix.prefixes=/dashboard
      - traefik.http.routers.admin-dashboard.middlewares=admin-dashboard-stripprefix
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.docker.network=traefik-public
      - traefik.http.middlewares.testheader.headers.customresponseheaders.X-Test-Header=TraefikProxy
    networks:
      - ragapp-network
  
  traefik:
    image: "traefik:v3.1"
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.fastapi-with-traefik.example.com`)
      - traefik.docker.network=traefik-public
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
      - traefik.http.routers.traefik-dashboard-https.middlewares=admin-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --api
    networks:
      - ragapp-network

networks:
  ragapp-network:
    external: true