services:
  manager:
    image: ragapp/manager
    build:
      context: src/manager
      args:
        # Build time variables to set the basePath for static files
        - APP_PATH=/manager
    entrypoint: ["/app/entrypoint.sh"]
    command: ["fastapi", "run", "main.py", "--root-path", "/manager"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - APP_PATH=/manager
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=8000
      - traefik.http.routers.admin-manager.rule=PathPrefix(`/manager`)
      - traefik.http.middlewares.strip-manager-path.stripprefix.prefixes=/manager
      - traefik.http.routers.admin-manager.middlewares=strip-manager-path,admin-auth
    networks:
      - ragapp-network
  
  traefik:
    image: "traefik:v3.1"
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.docker.network=ragapp-network
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --api
    networks:
      - ragapp-network

networks:
  ragapp-network:
    external: true