8d53880d-906d-404c-b5f4-91fb07567b85:
  created_at: 2024-09-16 02:53:57.746566
  name: Default
  role: Expert in answering questions using the provided knowledge
  system_prompt: You are a helpful assistant.
  tools:
    DuckDuckGo:
      config: {}
      enabled: false
    ImageGenerator:
      config:
        api_key: ''
      enabled: false
    Interpreter:
      config:
        api_key: null
      enabled: false
    OpenAPI:
      config:
        openapi_uri: null
      enabled: false
    QueryEngine:
      config: {}
      enabled: true
    Wikipedia:
      config: {}
      enabled: false
