agent1:
  name: Researcher
  role: Information Gatherer
  system_prompt: I'm helpful on using tool to get helpful information
  tools:
    DuckDuckGo:
      config: {}
      enabled: false
    ImageGenerator:
      config:
        api_key: ''
      enabled: false
    Interpreter:
      config:
        api_key: ''
      enabled: false
    OpenAPI:
      config: {}
      enabled: false
    QueryEngine:
      config: {}
      enabled: true
    Wikipedia:
      config: {}
      enabled: false
