8d53880d-906d-404c-b5f4-91fb07567b85:
  backstory: Expert in answering questions using the provided knowledge.
  created_at: 1721060837
  goal: To help answer questions using the provided knowledge.
  name: Default
  role: Assistant
  system_prompt: You are a helpful assistant.
  system_prompt_template: null
  tools:
    DuckDuckGo:
      config: {}
      custom_prompt: null
      enabled: false
    ImageGenerator:
      config:
        api_key: ''
      custom_prompt: null
      enabled: false
    Interpreter:
      config:
        api_key: null
      custom_prompt: null
      enabled: false
    OpenAPI:
      config:
        domain_headers: {}
        openapi_uri: null
      custom_prompt: null
      enabled: false
    QueryEngine:
      config: {}
      custom_prompt: null
      enabled: true
    Wikipedia:
      config: {}
      custom_prompt: null
      enabled: false
