services:
  traefik:
    image: "traefik:v3.1"
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.docker.network=ragapp-network
      # Default username: admin, password: admin
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME:-admin}:${HASHED_PASSWORD:-$$apr1$$3gG256rA$$BomHrC/uMhL807k/t7Wd6/}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --api
    networks:
      - ragapp-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - ragapp-network
  
  setup:
    image: curlimages/curl:latest
    networks:
      - ragapp-network
    volumes:
      - ../../scripts:/ragapp
    environment:
      - MODEL=${MODEL:-phi3:latest}
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAMES=cs50,cs101
      - DISTANCE_METRIC=Cosine
      - VECTOR_SIZE=768
    command: >
      /bin/sh -c "
      chmod +x /ragapp/create_qdrant_collection.sh &&
      /ragapp/create_qdrant_collection.sh"
    depends_on:
      - qdrant

  ragapp-cs50:
    build: ../..
    image: ragapp/ragapp:latest
    entrypoint: ["/app/scripts/app_entrypoint.sh"]
    command: ["fastapi", "run", "main.py"]
    volumes:
      - ./data/cs101-data:/app/data
    labels:
      - ragapp.app_name=cs50
      - traefik.enable=true
      - traefik.http.services.ragapp-cs50.loadbalancer.server.port=8000
      - traefik.http.routers.ragapp-cs50.rule=PathPrefix(`/a/cs50`)
      - traefik.http.middlewares.ragapp-cs50-strip-path.stripprefix.prefixes=/a/cs50
      - traefik.http.routers.ragapp-cs50.middlewares=ragapp-cs50-strip-path
      - traefik.http.routers.ragapp-cs50-admin.rule=PathRegexp(`/a/cs50/admin`)
      - traefik.http.routers.ragapp-cs50-admin.middlewares=admin-auth,ragapp-cs50-strip-path
    environment:
      - BASE_URL=/a/cs50
      - VECTOR_STORE_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=cs50
      - QDRANT_API_KEY=""
      - MODEL_PROVIDER=openai
      - MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - EMBEDDING_DIM=1024
    depends_on:
      - setup
    networks:
      - ragapp-network

  ragapp-cs101:
    build: ../..
    image: ragapp/ragapp:latest
    entrypoint: ["/app/scripts/app_entrypoint.sh"]
    command: ["fastapi", "run", "main.py"]
    volumes:
      - ./data/cs101-data:/app/data
    labels:
      - ragapp.app_name=cs101
      - traefik.enable=true
      - traefik.http.services.ragapp-cs101.loadbalancer.server.port=8000
      - traefik.http.routers.ragapp-cs101.rule=PathPrefix(`/a/cs101`)
      - traefik.http.middlewares.ragapp-cs101-strip-path.stripprefix.prefixes=/a/cs101
      - traefik.http.routers.ragapp-cs101.middlewares=ragapp-cs101-strip-path
      - traefik.http.routers.ragapp-cs101-admin.rule=PathRegexp(`/a/cs101/admin`)
      - traefik.http.routers.ragapp-cs101-admin.middlewares=admin-auth,ragapp-cs101-strip-path
    environment:
      - BASE_URL=/a/cs101
      - VECTOR_STORE_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=cs101
      - QDRANT_API_KEY=""
      - MODEL_PROVIDER=openai
      - MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - EMBEDDING_DIM=1024
    depends_on:
      - setup
    networks:
      - ragapp-network
  
  manager:
    image: ragapp/manager
    build: ../../src/manager
    entrypoint: ["/app/entrypoint.sh"]
    command: ["fastapi", "run", "main.py"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - BASE_URL=/manager
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=8000
      - traefik.http.routers.admin-manager.rule=PathPrefix(`/manager`)
      - traefik.http.middlewares.strip-manager-path.stripprefix.prefixes=/manager
      - traefik.http.routers.admin-manager.middlewares=strip-manager-path,admin-auth
    networks:
      - ragapp-network
  
networks:
  ragapp-network:
    external: true
