services:
  traefik:
    image: "traefik:v3.1"
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      # API and dashboard
      - traefik.docker.network=ragapp-network
      # Keycloak OpenID plugin configuration
      - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.KeycloakURL=http://localhost/auth
      - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.ClientID=ragapp
      # Secret from the example ragapp keycloak realm
      - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.ClientSecret=jh4yDlJ5QsBSafVNaqqLxEG3vKcYyNgD 
      - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.KeycloakRealm=ragapp
      - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.Scope=openid
      - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.TokenCookieName=AUTH_TOKEN
      - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.UseAuthHeader=false
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik_config.yml:ro
    command:
      - --configFile=/traefik_config.yml
    networks:
      - ragapp-network

  # IMPORTANT: This keycloak instance is for development purposes only
  # For production, you should use a more secure setup: https://www.keycloak.org/server/configuration-production
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev --import-realm --hostname=http://localhost/auth
    ports:
      - 8080:8080
    labels:
      - traefik.enable=true
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
      - traefik.http.routers.keycloak.rule=PathPrefix(`/auth`)
      - traefik.http.middlewares.keycloak-strip-path.stripprefix.prefixes=/auth
      - traefik.http.routers.keycloak.middlewares=keycloak-strip-path
    environment:
      # Keycloak admin user
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # Example realm: ragapp
      # test user: test
      # test password: 123456
    volumes:
      # Mount example realm data
      - ./keycloak/example/:/opt/keycloak/data/
    networks:
      - ragapp-network

  manager:
    image: ${MANAGER_IMAGE:-ragapp/manager:latest}
    build: ../../src/manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - BASE_URL=/manager
      - RAGAPP_IMAGE=${RAGAPP_IMAGE:-ragapp/ragapp:latest}
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=8000
      - traefik.http.routers.admin-manager.rule=PathPrefix(`/manager`)
      - traefik.http.middlewares.strip-manager-path.stripprefix.prefixes=/manager
      - traefik.http.routers.admin-manager.middlewares=my-keycloakopenid,strip-manager-path

    networks:
      - ragapp-network

  ragapp-cs50:
    build: ../../src/ragapp
    image: ${RAGAPP_IMAGE:-ragapp/ragapp:latest}
    volumes:
      - ./data/cs50-data:/app/data
    labels:
      - ragapp.app_name=cs50
      - traefik.enable=true
      - traefik.http.services.ragapp-cs50.loadbalancer.server.port=8000
      - traefik.http.routers.ragapp-cs50.rule=PathPrefix(`/a/cs50`)
      - traefik.http.routers.ragapp-cs50-admin.rule=PathRegexp(`/a/cs50/admin`)
      - traefik.http.routers.ragapp-cs50-admin.middlewares=my-keycloakopenid
      - traefik.http.routers.ragapp-cs50-management-api.rule=PathRegexp(`/a/cs50/api/management`)
      - traefik.http.routers.ragapp-cs50-management-api.middlewares=my-keycloakopenid
    environment:
      - BASE_URL=/a/cs50
      - FILESERVER_URL_PREFIX=/a/cs50/api/files
      - MODEL_PROVIDER=openai
      - MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - EMBEDDING_DIM=1024
    networks:
      - ragapp-network

  ragapp-cs101:
    build: ../../src/ragapp
    image: ${RAGAPP_IMAGE:-ragapp/ragapp:latest}
    volumes:
      - ./data/cs101-data:/app/data
    labels:
      - ragapp.app_name=cs101
      - traefik.enable=true
      - traefik.http.services.ragapp-cs101.loadbalancer.server.port=8000
      - traefik.http.routers.ragapp-cs101.rule=PathPrefix(`/a/cs101`)
      - traefik.http.routers.ragapp-cs101-admin.rule=PathRegexp(`/a/cs101/admin`)
      - traefik.http.routers.ragapp-cs101-admin.middlewares=my-keycloakopenid
      - traefik.http.routers.ragapp-cs101-management-api.rule=PathRegexp(`/a/cs101/api/management`)
      - traefik.http.routers.ragapp-cs101-management-api.middlewares=my-keycloakopenid
    environment:
      - BASE_URL=/a/cs101
      - FILESERVER_URL_PREFIX=/a/cs101/api/files
      - MODEL_PROVIDER=openai
      - MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - EMBEDDING_DIM=1024
    networks:
      - ragapp-network

networks:
  ragapp-network:
    name: ragapp-network
